default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: user_orders_development

test:
  <<: *default
  database: user_orders_test

production:
  <<: *default
  database: user_orders_production
  username: user_orders
  password: <%= ENV['USER_ORDERS_DATABASE_PASSWORD'] %>
